Regler för kodning
=> Regler för kodning

footer.css
=> Css-fil för footer skapad

startsida.html
=> Skapat startsida html + css

stories.html
=> Skapat css och html filer för stories

aboutUs.html
=> Skapat about us CSS och HTML filer

destinations.html
=> Skapat HTML och JS för destinations + länk

programs.html
=> Skapat HTML och JS för programs inkl länkning

database.js
=> Skapat js-fil för databasen samt lagt in databasen

Version2.txt
=> Skapade version 2 document

Version1 dokument
=> Version 1 dokument

aboutUs.css, aboutUs.html, destinations.css, destinations.html, programs.css, programs.html, startsida.css, startsida.html, stories.css, stories.html
=> Navbar placeholder för alla sidor

Versioner/Regler för kodning, aboutUs.css, destinations.css, footer.css, navbar.css, programs.css, startsida.css, stories.css
Inlagt på samtliga css-filer samt lagt in beskrivning för användning i regler för kodning
Fixed #6
=> Lagt in css variabler

aboutUs.html, destinations.html, footer.css, programs.html, startsida.html, stories.html
Fixed #45 
Fixed #42 
Fixed #36 
Fixed #31 
Fixed #27
=> Footers Installed

Versioner/pseudokod.txt
=> Börjat på pseudokod till dropdown

aboutUs.css, aboutUs.html
=> Textruta fixad i about us

destinations.css, destinations.html
=> Grund för popup lagd (Default display:none)

programs.css, programs.html
=> Popup grund fixad för "programs" (Default - Display:none)

startsida.css, startsida.html
=> Skapa top destinations  del (4 divar för resp. land + titel text + beskrivning + knapp till se alla) på startsida.html #25

programs.css, programs.html
=> #35 Drop down filters på plats

startsida.css, startsida.html
=> Stories startsida

CSS-filer/aboutUs.css, aboutUs.html
Fixed #91 
Stylat CSS så texten ligger rätt samt lagt in texten i html.
=> Skrivit about us text

CSS-filer/footer.css, aboutUs.html, destinations.html, programs.html, startsida.html, stories.html
=> 96 hantera footer

CSS-filer/navbar.css, aboutUs.html, destinations.html, programs.html, startsida.html, stories.html
=> Hantera länkning i navbar #100

CSS-filer/aboutUs.css, CSS-filer/destinations.css, CSS-filer/footer.css, CSS-filer/programs.css, CSS-filer/startsida.css, CSS-filer/stories.css
Ändrat margin i CSS så sidan endast får scroll vertikalt
=> Ändrat margin i CSS

JS-filer/programs.js, programs.html
OBS DENNA FUNGERAR ABSOLUT INTE
=> försökt lösa filter country på programme - OBS FUNKAR EJ

JS-filer/programs.js, programs.html
Fixat filtrering av första 3 filterna och så den visar rätt land och stad.
=> Filtrering och rendering av program
